// MCP preset templates — one-click connections for common software-development
// tooling. Each preset fills the connection form (name/transport/command/url/args)
// and declares the env vars it needs (e.g. an API key) so the UI can collect
// them and the connection is saved already configured.

export const MCP_PRESETS = [
  {
    id: 'github',
    name: 'GitHub',
    description: 'Read/search repos, issues, PRs, code. Official GitHub MCP server (stdio).',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'github-mcp-server'],
    env: [{ var: 'GITHUB_PERSONAL_ACCESS_TOKEN', label: 'GitHub PAT', kind: 'password' }],
  },
  {
    id: 'fetch',
    name: 'Fetch (read URLs)',
    description: 'Fetch and convert web pages / docs to markdown. Great for research.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-fetch'],
    env: [],
  },
  {
    id: 'playwright',
    name: 'Playwright (browser)',
    description: 'Drive a real browser: navigate, click, screenshot, extract. For E2E/web checks.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@playwright/mcp@latest'],
    env: [],
  },
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read/write/search local files under the given directories.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/home/ubuntu/specflow'],
    env: [],
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Inspect the local git repo: status, log, diff, blame.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'mcp-server-git', '--repository', '/home/ubuntu/specflow'],
    env: [],
  },
  {
    id: 'context7',
    name: 'Context7 (docs)',
    description: 'Up-to-date docs for thousands of libraries/frameworks. Great for code steps.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@upstash/context7-mcp'],
    env: [{ var: 'CONTEXT7_API_KEY', label: 'Context7 API key', kind: 'password', optional: true }],
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Web search via Brave API. Needs a (free) API key.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    env: [{ var: 'BRAVE_API_KEY', label: 'Brave API key', kind: 'password' }],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Post messages, read channels, search history (remote server, token).',
    transport: 'sse',
    url: 'https://mcp.slack.com/mcp',
    env: [{ var: 'SLACK_BOT_TOKEN', label: 'Slack bot token (xoxb-…)', kind: 'password' }],
  },
  {
    id: 'jira',
    name: 'Jira (Atlassian)',
    description: 'Query issues, transitions, comments on your Jira instance.',
    transport: 'sse',
    url: 'https://mcp.atlassian.com/sse',
    env: [{ var: 'ATLASSIAN_API_TOKEN', label: 'Atlassian API token', kind: 'password' }],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Search issues/events in Sentry, read scope/org/project info.',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', 'sentry-mcp'],
    env: [{ var: 'SENTRY_AUTH_TOKEN', label: 'Sentry auth token', kind: 'password' }],
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    description: 'Deeper multi-step reasoning for the agent (no key needed).',
    transport: 'stdio',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    env: [],
  },
];